[package]
name = "light"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
glam = "0.21.3"
lazy_static = "1.4.0"
envconfig = "0.10.0"
rand = "0.8.5"
image = "0.24.4"
rayon = "1.5.3"
dotenv = "0.15.0"
env_logger = "0.9.1"
log = "0.4.17"
